[package]
name = "ogcat"
version = "0.0.1"
edition = "2021"
description = "fast utils for phylogenomics"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
serde_json = "1.0"
tabled = "0.7.0"